# this file only contains the information that can go into the configuration file.
# you should copy relevant parts into a file called config.yaml in the same
# directory as pymdslides.py.

crop_images: true
text_color:
  - 0
  - 0
  - 0
  # colors are coded with RGB, 0-255, or a string: white|grey|black
background_color:
  - 0
  - 0
  - 0
  # colors are coded with RGB, 0-255, or a string: white|grey|black
dimensions:
  em: 18
  em_title: 26
  font_size_footer: 12
  font_size_standard: 34
  font_size_subtitle: 40
  font_size_title: 72
  internal_margin: 10
  margin_tiny_footer: 4
  page_height: 270
  page_margins:
    x0: 30
    x1: 30
    y0: 40
    y1: 40
  page_width: 480
  pixel_per_mm: 0.15
  tiny_footer_em: 6
layout: center
# layout can be center|image_center|image_left_half|image_left_small|image_right_half|image_right_small|image_fill
title_vertical_center: true|false
tiny_footer: Made with PYMDSLIDES
tiny_footer_color:
  - 128
  - 128
  - 128
  # colors are coded with RGB, 0-255, or a string: white|grey|black

fonts:
    font_file_standard: 'font_file_standard.ttf'
    font_file_standard_italic: 'font_file_standard_italic.ttf'
    font_file_standard_bold: 'font_file_standard_bold.ttf'
    font_file_standard_bolditalic: 'font_file_standard_bolditalic.ttf'
    font_file_title: 'font_file_title.ttf'
    font_file_footer: 'font_file_footer.ttf'
logo_path: 'logo.png'

